"""MCP tools for Quality Audit ISO/IEC 25010 v1 (on-demand)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fastmcp import FastMCP

from ..audit.orchestrator import run_audit
from ..audit.persistence import audit_dir, build_summary, update_project_meta
from ..audit.reporters import load_brand, write_json_report, write_pdf_report
from ..audit.schema import QualityReport, new_audit_id
from ..audit.signals import fetch_specbox_signals
from ..audit.tool_check import check_audit_tools
from .onboarding import _detect_infra, _detect_stack


def _detect_stack_adapter(project_path: Path) -> dict[str, Any]:
    stack_info = _detect_stack(project_path)
    infra = _detect_infra(project_path)
    return {
        "stack": stack_info.get("stack", "unknown"),
        "files_found": stack_info.get("files_found", []),
        "architecture_pattern": stack_info.get("architecture_pattern", "unknown"),
        "infra": infra,
    }


def register_audit_tools(mcp: FastMCP, engine_path: Path, state_path: Path) -> None:

    @mcp.tool
    def check_audit_tools_status(stack: str | None = None) -> dict:
        """Check which external audit tools are installed on the MCP host.

        **v6.0.1 — content-passing API**

        Args:
            stack: Optional stack identifier (``"flutter"``, ``"react"``,
                ``"python"``, ``"go"``, ``"google-apps-script"``). When
                supplied, the tool skips stack-irrelevant entries (e.g.
                ``npm audit`` for non-JS projects). The caller detects the
                stack locally and passes it here.

        Returns installed/missing lists plus ready-to-run install commands.
        Inspection runs on the MCP host (where the analyzers live in v6.0.1+
        until moved to the client per the audit migration plan).
        Nothing is installed automatically — this tool is read-only.
        """
        return check_audit_tools(stack=stack)

    @mcp.tool
    def submit_quality_audit(
        project: str,
        report: dict,
    ) -> dict:
        """Validate and accept a QualityReport built by the client.

        **v6.0.1 — content-passing API**

        Before v6.0.1, ``run_quality_audit`` orchestrated the 8 SQuaRE
        analyzers on the MCP host, which broke in remote MCP setups
        because the host has no access to the client codebase. v6.0.1
        moves the analyzers to ``.quality/scripts/audit/`` (executed on
        the client by the ``/audit`` skill); the skill builds the
        ``QualityReport`` locally and submits it here.

        This tool:
          - validates the report structure,
          - autogenerates ``audit_id`` server-side if the client did not
            provide one (format ``audit_YYYYMMDDTHHMMSSZ``); clients that
            need idempotency can pass their own ``audit_id`` and it is
            respected verbatim,
          - tags ``audit_tools_status`` based on the host's available tools,
          - returns the canonical dict ready to pass to
            :py:func:`attach_audit_evidence`.

        Args:
            project: Project name.
            report: Dict-serialised ``QualityReport`` (see
                ``server/audit/schema.py``). ``audit_id`` is optional —
                autogenerated if absent.
        """
        report = dict(report)  # defensive copy before mutating audit_id
        report.setdefault("audit_id", new_audit_id())
        try:
            parsed = QualityReport.from_dict(report)
        except (KeyError, ValueError, TypeError) as exc:
            return {"error": f"Invalid report payload: {exc}"}

        # The host can still attest which audit tools are installed locally,
        # which is informational for the skill that may have run them.
        tool_status = check_audit_tools(stack=None)
        data = parsed.to_dict()
        data["audit_tools_status"] = tool_status
        data["project"] = project
        if not tool_status["all_present"]:
            data["meta"].setdefault("warnings", []).append(
                f"{tool_status['missing_count']} audit tool(s) missing on "
                "the MCP host — informational only since v6.0.1; the client "
                "is expected to run analyzers locally via "
                ".quality/scripts/audit/."
            )
        return data

    @mcp.tool
    def run_quality_audit(
        project: str,
        report: dict | None = None,
        scope: str = "full",
        project_path: str = "",
    ) -> dict:
        """Deprecated v5.x audit orchestrator — use ``submit_quality_audit`` instead.

        **v6.0.1 — content-passing API**

        Pre-v6.0.1 callers passed ``project_path`` and the MCP host ran the
        8 SQuaRE analyzers, which is broken in remote MCP setups. v6.0.1
        keeps this tool registered for one release as a thin compatibility
        shim that delegates to ``submit_quality_audit`` when ``report`` is
        provided. When called with the legacy ``project_path`` form, it
        raises so the MCP envelope flags ``isError=true`` and clients that
        only inspect the envelope (not the structured payload) notice the
        deprecation instead of treating it as a silent success.
        """
        if report is not None:
            # Delegate to the sibling tool's underlying function (both are
            # defined in this closure). Previously accessed via .fn which
            # was always invalid from within the closure scope and only
            # avoided crashing because the test exercising this path was
            # skipped (issue surfaced in v6.0.2 when the test was repaired).
            return submit_quality_audit(project=project, report=report)

        raise RuntimeError(
            "run_quality_audit deprecated in v6.0.1 — replacement: "
            "submit_quality_audit. Run .quality/scripts/audit/ on the client "
            "to build a QualityReport, then call "
            f"submit_quality_audit(project={project!r}, report=...). "
            f"Legacy params received: scope={scope!r}, "
            f"project_path={project_path!r}."
        )

    @mcp.tool
    def attach_audit_evidence(
        project: str,
        report: dict,
    ) -> dict:
        """Persist a QualityReport as PDF + JSON under STATE_PATH evidence.

        Args:
            project: Project name — determines target directory.
            report: The QualityReport dict (possibly enriched by AG-10 with
                    justifications and recommendations).

        Returns paths of the persisted files and the updated project summary.
        """
        try:
            parsed = QualityReport.from_dict(report)
        except (KeyError, ValueError, TypeError) as exc:
            return {"error": f"Invalid report payload: {exc}"}

        out_dir = audit_dir(state_path, project)
        json_path = out_dir / f"{parsed.audit_id}.json"
        pdf_path = out_dir / f"{parsed.audit_id}.pdf"

        brand = load_brand(engine_path)
        if brand.warning:
            parsed.meta.setdefault("warnings", []).append(brand.warning)

        write_json_report(parsed, json_path)
        try:
            write_pdf_report(parsed, pdf_path, brand)
            pdf_status = "ok"
            pdf_error: str | None = None
        except Exception as exc:  # noqa: BLE001
            pdf_status = "error"
            pdf_error = str(exc)

        summary = build_summary(parsed, pdf_path, json_path)
        update_project_meta(state_path, project, summary)

        return {
            "project": project,
            "audit_id": parsed.audit_id,
            "json_path": str(json_path),
            "pdf_path": str(pdf_path) if pdf_status == "ok" else None,
            "pdf_status": pdf_status,
            "pdf_error": pdf_error,
            "global_score": parsed.global_score,
            "global_traffic_light": parsed.global_traffic_light.value,
            "summary": summary,
        }

    @mcp.tool
    def get_last_audit(project: str) -> dict:
        """Return the latest audit summary stored in the project's meta.json."""
        meta_file = state_path / "projects" / project / "meta.json"
        if not meta_file.exists():
            return {"error": f"No meta for project '{project}'"}
        try:
            data = json.loads(meta_file.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            return {"error": f"Could not read meta.json: {exc}"}
        return data.get("last_audit") or {"error": "No audits recorded yet"}
