"""Tests for the v6.0.1 content-passing audit tools (UC-618)."""
from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any

import pytest
from fastmcp import FastMCP


REPO_ROOT = Path(__file__).resolve().parent.parent


def _build_minimal_report() -> dict:
    """A QualityReport dict that round-trips through schema.from_dict.

    Built by hand against the schema in ``server/audit/schema.py`` so we
    do not depend on optional convenience constructors that may not exist.
    The contract this exercises is content-passing, not schema fidelity —
    we only need the smallest valid payload that ``QualityReport.from_dict``
    accepts.
    """
    return {
        "audit_schema_version": "1.0",
        "audit_id": "audit_test_fixture",
        "project": "t-proj",
        "project_path": "/tmp/t-proj",
        "commit": "deadbeef",
        "generated_at": "2026-05-25T10:00:00+00:00",
        "stack": {"stack": "python"},
        "global_score": 75.0,
        "global_traffic_light": "green",
        "characteristics": [],
        "tools_used": [],
        "meta": {},
    }


@pytest.fixture
def audit_tools(tmp_path):
    from server.tools.audit import register_audit_tools

    mcp = FastMCP(name="t-audit")
    register_audit_tools(mcp, engine_path=REPO_ROOT, state_path=tmp_path)

    async def _gather():
        out: dict[str, Any] = {}
        for n in (
            "check_audit_tools_status",
            "submit_quality_audit",
            "run_quality_audit",
            "attach_audit_evidence",
            "get_last_audit",
        ):
            tool = await mcp.get_tool(n)
            out[n] = tool.fn
        return out

    return asyncio.run(_gather())


class TestCheckAuditToolsStatus:
    def test_no_stack(self, audit_tools):
        result = audit_tools["check_audit_tools_status"]()
        assert "installed" in result or "missing" in result or "all_present" in result

    def test_python_stack(self, audit_tools):
        result = audit_tools["check_audit_tools_status"](stack="python")
        assert isinstance(result, dict)


class TestSubmitQualityAudit:
    def test_invalid_report_returns_error(self, audit_tools):
        result = audit_tools["submit_quality_audit"](
            project="proj-x",
            report={"not": "valid"},
        )
        assert "error" in result

    def test_valid_minimal_report_round_trips(self, audit_tools):
        try:
            payload = _build_minimal_report()
        except (AttributeError, TypeError):
            pytest.skip("QualityReport.empty() not available in this schema version")
        result = audit_tools["submit_quality_audit"](
            project="t-proj",
            report=payload,
        )
        assert "error" not in result
        assert result["project"] == "t-proj"
        assert "audit_tools_status" in result

    # Issue #61 (v6.0.2): audit_id is optional — autogenerated server-side
    # if absent, respected verbatim if the client provides one for idempotency.

    def test_audit_id_autogenerated_when_missing(self, audit_tools):
        try:
            payload = _build_minimal_report()
        except (AttributeError, TypeError):
            pytest.skip("QualityReport.empty() not available")
        payload.pop("audit_id", None)
        result = audit_tools["submit_quality_audit"](
            project="t-proj",
            report=payload,
        )
        assert "error" not in result
        assert result.get("audit_id", "").startswith("audit_")

    def test_audit_id_respected_when_provided(self, audit_tools):
        try:
            payload = _build_minimal_report()
        except (AttributeError, TypeError):
            pytest.skip("QualityReport.empty() not available")
        payload["audit_id"] = "audit_clientside_idempotent_v1"
        result = audit_tools["submit_quality_audit"](
            project="t-proj",
            report=payload,
        )
        assert "error" not in result
        assert result["audit_id"] == "audit_clientside_idempotent_v1"


class TestRunQualityAuditDeprecation:
    # Issue #60 (v6.0.2): legacy call without report must raise so the MCP
    # envelope sets isError=true. Previously returned a dict with `error`
    # that left isError=false — silent success for envelope-only clients.

    def test_no_report_raises_for_iserror_envelope(self, audit_tools):
        with pytest.raises(RuntimeError) as excinfo:
            audit_tools["run_quality_audit"](
                project="proj-x",
                project_path="/tmp/anything",
            )
        msg = str(excinfo.value)
        assert "deprecated" in msg.lower()
        assert "submit_quality_audit" in msg
        assert "v6.0.1" in msg

    def test_with_report_delegates_to_submit(self, audit_tools):
        try:
            payload = _build_minimal_report()
        except (AttributeError, TypeError):
            pytest.skip("QualityReport.empty() not available")
        result = audit_tools["run_quality_audit"](
            project="t-proj",
            report=payload,
        )
        assert "error" not in result
        assert result["project"] == "t-proj"


class TestGetLastAudit:
    def test_no_meta_returns_error(self, audit_tools):
        result = audit_tools["get_last_audit"](project="nonexistent")
        assert "error" in result
